#version 430
#extension GL_ARB_bindless_texture : require
#extension GL_ARB_gpu_shader_int64 : require

// ---------------
// THREAD GROUP
// ---------------
layout(local_size_x = 16, local_size_y = 16) in;

// ---------------------
// ACCUMULATION IMAGE
// ---------------------
layout(rgba32f, binding = 0) coherent uniform image2D imgAccum;
layout(rgba32f, binding = 4) uniform writeonly image2D imgGbuffer;

// ---------
// TYPES
// --------
struct Sphere {
    vec4 centerRadius;

    vec3 diffuse;   float kd;
    vec3 specular;  float ks;
    float shininess; float emissionR, emissionG, emissionB;
    int Material_type, textureIdx; float emissionStrength; int normalMapIdx;
};

struct Square {
    vec4 a;
    vec4 b;
    vec4 c;
    vec4 d;

    vec3 diffuse;   float kd;
    vec3 specular;  float ks;
    float shininess; float emissionR, emissionG, emissionB;
    int Material_type, textureIdx; float emissionStrength; int normalMapIdx;
};

struct Mesh {
    int Material_type;
    int triOffset;
    int triCount;
    int pad0;
};

struct BVHNode {
    float minX, minY, minZ;
    int rightChildOrPrim;
    float maxX, maxY, maxZ;
    int triangleCount;
};

struct TriangleIndexed {
    uint v0, v1, v2, matIdx;
};

struct Vertex {
    vec4 pos; // xyz, pad
    vec4 normal; // xyz, pad
    vec4 uv; // uv, pad, pad
};

struct Material {
    vec3 diffuse; float kd;
    vec3 specular; float ks;
    float shininess; float emissionStrength; int normalMapIdx; int type;
    int textureIdx; float emissionR, emissionG, emissionB;
};

struct Light {
    vec4 posIntensity;
    vec4 color;
    float lightRadius, pad1, pad2, pad3;
};

// --------
// SSBO
// --------
layout(std430, binding = 1) buffer Spheres { Sphere spheres[]; };
layout(std430, binding = 2) buffer Lights  { Light  lights[];  };
layout(std430, binding = 3) buffer Squares { Square squares[]; };
layout(std430, binding = 4) buffer Meshes { Mesh meshes[]; };
layout(std430, binding = 5) buffer Triangles { TriangleIndexed triangles[]; };
layout(std430, binding = 6) buffer BVHNodes { BVHNode nodes[]; };
layout(std430, binding = 7) buffer Vertices { Vertex vertices[]; };
layout(std430, binding = 8) buffer Materials { Material materials[]; };
layout(std430, binding = 9) buffer TextureHandles { uint64_t handles[]; };

// -----------
// UNIFORMS
// -----------
layout(location = 0) uniform int u_sphereCount;
layout(location = 1) uniform int u_lightCount;
layout(location = 2) uniform vec3 u_camPos;
layout(location = 3) uniform vec3 u_camFront;
layout(location = 4) uniform vec3 u_camRight;
layout(location = 5) uniform vec3 u_camUp;
layout(location = 6) uniform float u_fovDeg;
layout(location = 7) uniform int u_width;
layout(location = 8) uniform int u_height;
layout(location = 9) uniform int u_squareCount;
layout(location = 10) uniform int u_frameIndex;
layout(location = 11) uniform int u_spp;
layout(location = 12) uniform int u_triangleCount;
layout(location = 13) uniform int u_meshCount;
layout(location = 14) uniform int u_maxBounces;
layout(location = 15) uniform int u_shadowSamples;
layout(location = 16) uniform float u_lensRadius;
layout(location = 17) uniform float u_focalDistance;
layout(location = 18) uniform int u_enableDoF;
layout(location = 19) uniform vec3 u_bgColor;

// -------
// ALEA
// -------
uint hash_u(uint x)
{
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

float randf(inout uint state)
{
    state = hash_u(state);
    return float(state) / 4294967296.0;
}

// -----------------------
// hemisphere sampling
// -----------------------

vec3 randomHemisphere(vec3 N, inout uint seed)
{
    float u = randf(seed);
    float v = randf(seed);

    float phi = 2.0 * 3.14159265358979323846 * u;

    float cosTheta = sqrt(v);
    float sinTheta = sqrt(max(0.0, 1.0 - cosTheta * cosTheta));

    vec3 T = normalize(abs(N.x) > 0.1 ? cross(N, vec3(0,1,0)) : cross(N, vec3(1,0,0)));
    vec3 B = cross(N, T);

    return normalize(
        T * (cos(phi) * sinTheta) +
        B * (sin(phi) * sinTheta) +
        N * cosTheta
    );
}

vec3 sampleUniformSphere(inout uint seed)
{
    float u = randf(seed);
    float v = randf(seed);
    float z = 1.0 - 2.0 * u;
    float phi = 2.0 * 3.14159265358979323846 * v;
    float r = sqrt(max(0.0, 1.0 - z * z));
    return vec3(r * cos(phi), r * sin(phi), z);
}

vec2 concentricSampleDisk(vec2 u)
{
    float ox = 2.0 * u.x - 1.0;
    float oy = 2.0 * u.y - 1.0;
    if (ox == 0.0 && oy == 0.0) return vec2(0.0);
    float r, theta;
    if (abs(ox) > abs(oy)) {
        r = ox;
        theta = (3.14159265359 / 4.0) * (oy / ox);
    } else {
        r = oy;
        theta = (3.14159265359 / 2.0) - (3.14159265359 / 4.0) * (ox / oy);
    }
    return r * vec2(cos(theta), sin(theta));
}

// -------------
// HIT STRUCT
// -------------

struct Hit {
    float t;
    vec3 pos;
    vec3 normal;
    vec2 uv;
    vec3 tangent;

    vec3 diffuse;
    float kd;

    vec3 specular;
    float ks;

    float shininess;
    int Material_type;
    int textureIdx;
    int normalMapIdx;

    vec3 emission;
    float emissionStrength;
};

// ---------------
// INTERSECTIONS
// ---------------
bool intersectSphere(vec3 ro, vec3 rd, vec4 cR, out float t)
{
    vec3 oc = ro - cR.xyz;
    float r = cR.w;
    float b = dot(oc, rd);
    float c = dot(oc, oc) - r*r;
    float disc = b*b - c;
    if (disc < 0.0) return false;

    float sq = sqrt(disc);
    float t1 = -b - sq;
    float t2 = -b + sq;

    t = (t1 > 1e-4) ? t1 : ((t2 > 1e-4) ? t2 : -1.0);
    return t > 0.0;
}

bool intersectQuad(vec3 ro, vec3 rd, Square sq,
                   out float tHit, out vec3 normalOut, out vec3 diffuse, out vec3 specular, out float kd,out float ks,out float shininess, out int matType, out vec2 uvOut, out int texIdx, out vec3 emission, out float emissionStrength, out vec3 tangentOut, out int normalMapIdx)
{
    vec3 A = sq.a.xyz;
    vec3 B = sq.b.xyz;
    vec3 C = sq.c.xyz;
    vec3 D = sq.d.xyz;

    vec3 N = normalize(cross(B - A, D - A));
    float denom = dot(N, rd);
    if (abs(denom) < 1e-6) return false;

    float t = dot(A - ro, N) / denom;
    if (t <= 1e-4) return false;

    vec3 P = ro + rd * t;

    vec3 c1 = cross(B - A, P - A);
    vec3 c2 = cross(C - B, P - B);
    vec3 c3 = cross(A - C, P - C);

    if (dot(c1,N) >= 0.0 && dot(c2,N) >= 0.0 && dot(c3,N) >= 0.0) {
        tHit = t; normalOut = N; diffuse = sq.diffuse;
        specular=sq.specular;
        kd=sq.kd;
        ks=sq.ks;
        shininess=sq.shininess;
        matType = sq.Material_type;
        texIdx = sq.textureIdx;
        emission = vec3(sq.emissionR, sq.emissionG, sq.emissionB);
        emissionStrength = sq.emissionStrength;
        normalMapIdx = sq.normalMapIdx;
        tangentOut = normalize(B - A);

        float areaABC = length(cross(B-A, C-A));
        float u = length(c2) / areaABC;
        float v = length(c3) / areaABC;
        float w = length(c1) / areaABC;
        uvOut = u*vec2(0,0) + v*vec2(1,0) + w*vec2(1,1);

        return true;
    }

    vec3 c4 = cross(C - A, P - A);
    vec3 c5 = cross(D - C, P - C);
    vec3 c6 = cross(A - D, P - D);

    if (dot(c4,N) >= 0.0 && dot(c5,N) >= 0.0 && dot(c6,N) >= 0.0) {
        tHit = t;
        normalOut = N;
        diffuse = sq.diffuse;
        specular=sq.specular;
        kd=sq.kd;
        ks=sq.ks;
        shininess=sq.shininess;
        matType = sq.Material_type;
        texIdx = sq.textureIdx;
        emission = vec3(sq.emissionR, sq.emissionG, sq.emissionB);
        emissionStrength = sq.emissionStrength;
        normalMapIdx = sq.normalMapIdx;
        tangentOut = normalize(B - A);

        float areaACD = length(cross(C-A, D-A));
        float u = length(c5) / areaACD;
        float v = length(c6) / areaACD;
        float w = length(c4) / areaACD;
        uvOut = u*vec2(0,0) + v*vec2(1,1) + w*vec2(0,1);

        return true;
    }

    return false;
}

// ---------
// Intersection des triangles
// ---------

bool intersectTri(vec3 ro, vec3 rd, TriangleIndexed tri,
                    out float tHit, out vec3 normalOut, out vec3 diffuse, out vec3 specular, out float kd,out float ks,out float shininess, out int matType, out vec2 uvOut, out int texIdx, out vec3 emission, out float emissionStrength, out vec3 tangentOut, out int normalMapIdx){

    vec3 v0 = vertices[tri.v0].pos.xyz;
    vec3 v1 = vertices[tri.v1].pos.xyz;
    vec3 v2 = vertices[tri.v2].pos.xyz;

    vec3 e1 = v1 - v0;
    vec3 e2 = v2 - v0;

    vec3 pvec = cross(rd, e2);
    float det = dot(e1, pvec);
    float detInv = 1.0/det;

    if (abs(det) < 1e-6) return false;

    vec3 tvec = ro - v0;
    float u = dot(tvec, pvec) * detInv;
    if (u < 0.0 || u > 1.0) return false;

    vec3 qvec = cross(tvec, e1);
    float v = dot(rd, qvec) * detInv;
    if (v < 0.0 || u + v > 1.0) return false;

    float t = dot(e2, qvec) * detInv;
    if (t <= 1e-4) return false;

    tHit = t;

    vec3 n0 = vertices[tri.v0].normal.xyz;
    vec3 n1 = vertices[tri.v1].normal.xyz;
    vec3 n2 = vertices[tri.v2].normal.xyz;
    normalOut = normalize((1.0 - u - v) * n0 + u * n1 + v * n2);

    vec2 uv0 = vertices[tri.v0].uv.xy;
    vec2 uv1 = vertices[tri.v1].uv.xy;
    vec2 uv2 = vertices[tri.v2].uv.xy;
    uvOut = (1.0 - u - v) * uv0 + u * uv1 + v * uv2;

    vec2 deltaUV1 = uv1 - uv0;
    vec2 deltaUV2 = uv2 - uv0;
    float f = 1.0 / (deltaUV1.x * deltaUV2.y - deltaUV2.x * deltaUV1.y);
    
    tangentOut.x = f * (deltaUV2.y * e1.x - deltaUV1.y * e2.x);
    tangentOut.y = f * (deltaUV2.y * e1.y - deltaUV1.y * e2.y);
    tangentOut.z = f * (deltaUV2.y * e1.z - deltaUV1.y * e2.z);
    tangentOut = normalize(tangentOut);

    Material mat = materials[tri.matIdx];
    diffuse = mat.diffuse;
    specular = mat.specular;
    kd = mat.kd;
    ks = mat.ks;
    shininess = mat.shininess;
    matType = mat.type;
    texIdx = mat.textureIdx;
    emission = vec3(mat.emissionR, mat.emissionG, mat.emissionB);
    emissionStrength = mat.emissionStrength;
    normalMapIdx = mat.normalMapIdx;

    return true;
}

// ---------
// AABB Intersection
// ---------

bool intersectAABB(vec3 ro, vec3 invRd, vec3 aabbMin, vec3 aabbMax, float tMin, float tMax) {
    vec3 t0 = (aabbMin - ro) * invRd;
    vec3 t1 = (aabbMax - ro) * invRd;

    vec3 tPetit = min(t0, t1);
    vec3 tGros  = max(t0, t1);

    float tmin = max(tMin, max(tPetit.x, max(tPetit.y, tPetit.z)));
    float tmax = min(tMax, min(tGros.x, min(tGros.y, tGros.z)));

    return tmin <= tmax;
}

// -------
// OMBRE
// -------

bool traceShadow(vec3 ro, vec3 rd, float maxDist)
{
    for (int i = 0; i < u_sphereCount; ++i)
    {
        float t;
        if (intersectSphere(ro, rd, spheres[i].centerRadius, t)) {
            if (t < maxDist) {
                if (spheres[i].Material_type == 2) continue;
                return true;
            }
        }
    }

    for (int i = 0; i < u_squareCount; ++i)
    {
        vec3 A = squares[i].a.xyz;
        vec3 B = squares[i].b.xyz;
        vec3 D = squares[i].d.xyz;
        vec3 N = normalize(cross(B - A, D - A));
        float denom = dot(N, rd);
        if (abs(denom) > 1e-6) {
            float t = dot(A - ro, N) / denom;
            if (t > 1e-4 && t < maxDist) {
                vec3 P = ro + rd * t;
                vec3 C = squares[i].c.xyz;
                
                bool hit = false;
                if (dot(cross(B - A, P - A), N) >= 0.0 &&
                    dot(cross(C - B, P - B), N) >= 0.0 &&
                    dot(cross(A - C, P - C), N) >= 0.0) hit = true;
                else if (dot(cross(C - A, P - A), N) >= 0.0 &&
                         dot(cross(D - C, P - C), N) >= 0.0 &&
                         dot(cross(A - D, P - D), N) >= 0.0) hit = true;

                if (hit) {
                    if (squares[i].Material_type == 2) continue;
                    return true;
                }
            }
        }
    }

    if (u_triangleCount > 0) {
        vec3 invRd = 1.0 / rd;
        int stack[32];
        int stackPtr = 0;
        stack[stackPtr++] = 0;

        while (stackPtr > 0) {
            int nodeIdx = stack[--stackPtr];
            BVHNode node = nodes[nodeIdx];

            if (!intersectAABB(ro, invRd, vec3(node.minX, node.minY, node.minZ),
                                          vec3(node.maxX, node.maxY, node.maxZ), 1e-4, maxDist)) {
                continue;
            }

            if (node.triangleCount > 0) {
                for (int i = 0; i < node.triangleCount; ++i) {
                    int triIdx = node.rightChildOrPrim + i;
                    TriangleIndexed tri = triangles[triIdx];

                    vec3 v0 = vertices[tri.v0].pos.xyz;
                    vec3 v1 = vertices[tri.v1].pos.xyz;
                    vec3 v2 = vertices[tri.v2].pos.xyz;

                    vec3 e1 = v1 - v0;
                    vec3 e2 = v2 - v0;
                    vec3 pvec = cross(rd, e2);
                    float det = dot(e1, pvec);
                    float detInv = 1.0/det;

                    if (abs(det) > 1e-6) {
                        vec3 tvec = ro - v0;
                        float u = dot(tvec, pvec) * detInv;
                        if (u >= 0.0 && u <= 1.0) {
                            vec3 qvec = cross(tvec, e1);
                            float v = dot(rd, qvec) * detInv;
                            if (v >= 0.0 && u + v <= 1.0) {
                                float t = dot(e2, qvec) * detInv;
                                if (t > 1e-4 && t < maxDist) {
                                    if (materials[tri.matIdx].type == 2) continue;
                                    return true;
                                }
                            }
                        }
                    }
                }
            } else {
                int leftChild = nodeIdx + 1;
                int rightChild = node.rightChildOrPrim;
                stack[stackPtr++] = rightChild;
                stack[stackPtr++] = leftChild;
            }
        }
    }

    return false;
}

// ---------
// TRACE
// ---------

bool trace(vec3 ro, vec3 rd, out Hit hit)
{
    hit.t = 1e30;
    hit.textureIdx = -1;
    hit.normalMapIdx = -1;
    hit.uv = vec2(0.0);
    bool found = false;

    // Spheres
    for (int i = 0; i < u_sphereCount; ++i)
    {
        float t;
        if (intersectSphere(ro, rd, spheres[i].centerRadius, t)) {
            if (t < hit.t) {
                hit.t = t;
                hit.pos = ro + rd * t;
                hit.normal = normalize(hit.pos - spheres[i].centerRadius.xyz);

                hit.diffuse = spheres[i].diffuse;
                hit.kd = spheres[i].kd;
                hit.specular = spheres[i].specular;
                hit.ks = spheres[i].ks;
                hit.shininess = spheres[i].shininess;
                hit.Material_type = spheres[i].Material_type;
                hit.textureIdx = spheres[i].textureIdx;
                hit.normalMapIdx = spheres[i].normalMapIdx;
                hit.emission = vec3(spheres[i].emissionR, spheres[i].emissionG, spheres[i].emissionB);
                hit.emissionStrength = spheres[i].emissionStrength;

                vec3 N = hit.normal;
                float u = 0.5 + atan(N.z, N.x) / (2.0 * 3.14159265);
                float v = 0.5 + asin(N.y) / 3.14159265;
                hit.uv = vec2(u, v);
                
                hit.tangent = normalize(vec3(-N.z, 0.0, N.x));
                if (length(hit.tangent) < 0.001) hit.tangent = vec3(1,0,0);

                found = true;
            }
        }

    }

    // Squares
    for (int i = 0; i < u_squareCount; ++i)
    {
        float t; vec3 n; vec3 diffuse;
        float kd; float ks; float shininess;
        vec3 specular;
        int matType; vec2 uv; int texIdx;
        vec3 emission; float emissionStrength;
        vec3 tangent; int normalMapIdx;

        if (intersectQuad(ro, rd, squares[i], t, n, diffuse,specular,kd,ks,shininess, matType, uv, texIdx, emission, emissionStrength, tangent, normalMapIdx))
        {
            if (t < hit.t) {
                hit.t = t;
                hit.pos = ro + rd * t;
                hit.normal = n;
                hit.diffuse = diffuse;
                hit.specular=specular;
                hit.kd=kd;
                hit.ks=ks;
                hit.shininess=shininess;
                hit.Material_type = matType;
                hit.textureIdx = texIdx;
                hit.normalMapIdx = normalMapIdx;
                hit.uv = uv;
                hit.emission = emission;
                hit.emissionStrength = emissionStrength;
                hit.tangent = tangent;
                found = true;
            }
        }
    }

    // BVH
    if (u_triangleCount > 0) {
        vec3 invRd = 1.0 / rd;
        int stack[32];
        int stackPtr = 0;
        stack[stackPtr++] = 0;

        while (stackPtr > 0) {
            int nodeIdx = stack[--stackPtr];
            BVHNode node = nodes[nodeIdx];

            if (!intersectAABB(ro, invRd, vec3(node.minX, node.minY, node.minZ),
                                          vec3(node.maxX, node.maxY, node.maxZ), 0.001, hit.t)) {
                continue;
            }

            if (node.triangleCount > 0) {
                for (int i = 0; i < node.triangleCount; ++i) {
                    int triIdx = node.rightChildOrPrim + i;
                    float t; vec3 n; vec3 diffuse;
                    float kd; float ks; float shininess;
                    vec3 specular;
                    int matType;
                    vec2 uv; int texIdx;
                    vec3 emission; float emissionStrength;
                    vec3 tangent; int normalMapIdx;

                    if (intersectTri(ro, rd, triangles[triIdx], t, n, diffuse, specular, kd, ks, shininess, matType, uv, texIdx, emission, emissionStrength, tangent, normalMapIdx)) {
                        if (t < hit.t) {
                            hit.t = t;
                            hit.pos = ro + rd * t;
                            hit.normal = n;
                            hit.diffuse = diffuse;
                            hit.kd = kd;
                            hit.specular = specular;
                            hit.ks = ks;
                            hit.shininess = shininess;
                            hit.Material_type = matType;
                            hit.uv = uv;
                            hit.textureIdx = texIdx;
                            hit.normalMapIdx = normalMapIdx;
                            hit.emission = emission;
                            hit.emissionStrength = emissionStrength;
                            hit.tangent = tangent;
                            found = true;
                        }
                    }
                }
            } else {
                int leftChild = nodeIdx + 1;
                int rightChild = node.rightChildOrPrim;

                stack[stackPtr++] = rightChild;
                stack[stackPtr++] = leftChild;
            }
        }
    }

    return found;
}

// ------
// MATERIALS
// ------

void mirror(in Hit h, inout vec3 ro, inout vec3 rd, inout vec3 throughput) {
    rd = reflect(rd, h.normal);
    ro = h.pos + h.normal * 1e-3;
    throughput *= h.specular;
}

void glass(in Hit h, inout vec3 ro, inout vec3 rd, inout vec3 throughput, inout uint seed) {
    float n1 = 1.0;
    float n2 = 1.5;
    float eta = n1 / n2;

    vec3 I = normalize(rd);
    vec3 N = h.normal;
    float cosi = clamp(dot(I, N), -1.0, 1.0);

    if (cosi > 0.0) {
        N = -N;
        float tmp = n1; n1 = n2; n2 = tmp;
        eta = n1 / n2;
        cosi = -cosi;
    }

    float k = 1.0 - eta * eta * (1.0 - cosi * cosi);
    
    float r0 = (n1 - n2) / (n1 + n2);
    r0 = r0 * r0;
    float fresnel = r0 + (1.0 - r0) * pow(1.0 - abs(cosi), 5.0);

    if (k < 0.0 || randf(seed) < fresnel) {
        rd = reflect(I, N);
        ro = h.pos + N * 1e-3;
    }
    else {
        rd = eta * I - (eta * cosi + sqrt(k)) * N;
        ro = h.pos - N * 1e-3;
    }

    throughput *= vec3(1.0);
}

// ------
// MAIN 
// ------

void main()
{
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);
    if (px.x >= u_width || px.y >= u_height) return;

    uint seed = uint(px.x) + uint(px.y) * 1664525u + uint(u_frameIndex) * 1013904223u;
    vec3 finalRadiance = vec3(0.0);

    for (int s = 0; s < u_spp; s++)
    {
        uint sseed = hash_u(seed + uint(s));
        float jx = randf(sseed);
        float jy = randf(sseed);

        vec2 uv = ((vec2(px) + vec2(jx, jy)) / vec2(u_width, u_height)) * 2.0 - 1.0;

        float fov = radians(u_fovDeg);
        float aspect = float(u_width) / float(u_height);
        float sx = uv.x * aspect * tan(fov * 0.5);
        float sy = uv.y * tan(fov * 0.5);

        vec3 ro = u_camPos;
        vec3 rd = normalize(u_camRight * sx + u_camUp * sy + u_camFront);

        if (u_enableDoF != 0 && u_lensRadius > 1e-6) {
            vec3 focalPoint = ro + rd * u_focalDistance;

            float r1 = randf(sseed);
            float r2 = randf(sseed);
            vec2 lensSample = concentricSampleDisk(vec2(r1, r2)) * u_lensRadius;

            vec3 newRo = u_camPos + u_camRight * lensSample.x + u_camUp * lensSample.y;
            vec3 newRd = normalize(focalPoint - newRo);

            ro = newRo;
            rd = newRd;
        }

        vec3 throughput = vec3(1.0);
        vec3 radiance = vec3(0.0);
        const int MAX_BOUNCES = u_maxBounces;

        for (int bounce = 0; bounce < MAX_BOUNCES; bounce++)
        {
            Hit h;

            if (!trace(ro, rd, h))
            {
                radiance += throughput * u_bgColor;

                if (bounce == 0) {
                    imageStore(imgGbuffer, px, vec4(0,0,0, 1000.0));
                }
                break;
            }

            // Normal Mapping
            if (h.normalMapIdx >= 0) {
                uint64_t handle = handles[h.normalMapIdx];
                sampler2D s = sampler2D(handle);
                vec3 mapN = texture(s, h.uv).rgb;
                mapN = mapN * 2.0 - 1.0;
                
                vec3 T = normalize(h.tangent - h.normal * dot(h.normal, h.tangent));
                vec3 B = cross(h.normal, T);
                mat3 TBN = mat3(T, B, h.normal);
                
                h.normal = normalize(TBN * mapN);
            }

            // Emission
            radiance += throughput * h.emission * h.emissionStrength;

            if (bounce == 0) {
                imageStore(imgGbuffer, px, vec4(h.normal, h.t));
            }

            // --- Miroir ---
            if (h.Material_type == 1) {
                mirror(h, ro, rd, throughput);
                continue;
            }

            // --- Verre ---
            if (h.Material_type == 2) {
                glass(h, ro, rd, throughput, sseed);
                continue;
            }

            vec3 V = normalize(-rd);
            
            vec3 albedo = h.diffuse;
            if (h.textureIdx >= 0) {
                uint64_t handle = handles[h.textureIdx];
                sampler2D s = sampler2D(handle);
                albedo = texture(s, h.uv).rgb;
            }

            vec3 directLight = vec3(0.0);

            for (int li = 0; li < u_lightCount; li++)
            {
                vec3 Lpos = lights[li].posIntensity.xyz;
                float intensity = lights[li].posIntensity.w;
                vec3 lightColor = lights[li].color.rgb;
                float lightRadius = lights[li].lightRadius;

                vec3 accumContribution = vec3(0.0);

                for (int s = 0; s < u_shadowSamples; s++)
                {
                    vec3 rnd = sampleUniformSphere(seed);
                    vec3 lightPoint = Lpos + rnd * lightRadius;

                    vec3 toLight = lightPoint - h.pos;
                    float distSample = length(toLight);
                    vec3 Ls = toLight / distSample;

                    bool hitSomething = traceShadow(h.pos + h.normal * 1e-3, Ls, distSample - 1e-3);
                    bool visible = !hitSomething;

                    if (visible)
                    {
                        float attenuation = 1.0 / (distSample * distSample);
                        float diff = max(dot(h.normal, Ls), 0.0);
                        vec3 diffuseTerm = h.kd * albedo * diff;

                        vec3 R = reflect(-Ls, h.normal);
                        float spec = pow(max(dot(R, V), 0.0), h.shininess);
                        vec3 specTerm = h.ks * h.specular * spec;

                        accumContribution += (diffuseTerm + specTerm) * lightColor * intensity * attenuation;
                    }
                }

                directLight += accumContribution / float(u_shadowSamples);
            }

            radiance += throughput * directLight;
            throughput *= albedo;

            if (bounce > 2)
            {
                float p = clamp(max(max(throughput.r, throughput.g), throughput.b), 0.05, 0.95);
                if (randf(sseed) > p) break;
                throughput /= p;
            }

            ro = h.pos + h.normal * 1e-3;
            rd = randomHemisphere(h.normal, sseed);
        }

        finalRadiance += radiance;
    }

    finalRadiance /= float(u_spp);
    // finalRadiance = min(finalRadiance, vec3(2.0)); // Removed aggressive clamping

    imageStore(imgAccum, px, vec4(finalRadiance, 1.0));
}
